#!/usr/bin/env bash
#
# xray-manager — one-command Docker installer (Raspberry Pi / any Linux).
#
# It installs Docker (if missing), fetches the source, generates a config with a
# random session secret and password, then builds and starts the panel as a
# container that always restarts (incl. after a reboot). xray-core is baked into
# the image, so there is nothing else to install.
#
# Quick start — run ONE of these on the target machine:
#
#   curl -fsSL https://raw.githubusercontent.com/SaeedCodez/mikrotik-xray-manager/main/docker-install.sh | sudo bash
#
#   # …or, if you already cloned the repo:
#   sudo ./docker-install.sh
#
# Manage it afterwards from the install dir:
#   docker compose logs -f          # live logs
#   docker compose restart          # restart
#   docker compose down             # stop & remove
#   docker compose up -d --build    # update after a `git pull`
#
# Env overrides:  APP_PORT=9090  APP_PASSWORD=secret  INSTALL_DIR=/opt/xray-manager

set -euo pipefail

REPO="SaeedCodez/mikrotik-xray-manager"
INSTALL_DIR="${INSTALL_DIR:-/opt/xray-manager}"
APP_PORT="${APP_PORT:-8080}"
APP_PASSWORD="${APP_PASSWORD:-}"
GENERATED_PASS=""

# ---- pretty output --------------------------------------------------------
if [ -t 1 ]; then
  C_OK=$'\033[32m'; C_WARN=$'\033[33m'; C_ERR=$'\033[31m'; C_DIM=$'\033[2m'; C_OFF=$'\033[0m'
else
  C_OK=""; C_WARN=""; C_ERR=""; C_DIM=""; C_OFF=""
fi
log()  { printf '%s==>%s %s\n' "$C_OK"   "$C_OFF" "$*"; }
warn() { printf '%s[!]%s %s\n' "$C_WARN" "$C_OFF" "$*" >&2; }
die()  { printf '%s[x]%s %s\n' "$C_ERR"  "$C_OFF" "$*" >&2; exit 1; }

need_root() {
  [ "$(id -u)" -eq 0 ] || die "Please run as root: pipe into 'sudo bash', or 'sudo ./docker-install.sh'."
}

# ---- docker + compose -----------------------------------------------------
ensure_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    log "Docker not found — installing via get.docker.com (this can take a few minutes)…"
    curl -fsSL https://get.docker.com | sh || die "Docker install failed."
  else
    log "Docker is already installed."
  fi
  command -v systemctl >/dev/null 2>&1 && systemctl enable --now docker >/dev/null 2>&1 || true

  if ! docker compose version >/dev/null 2>&1; then
    log "Installing the Docker Compose plugin…"
    if command -v apt-get >/dev/null 2>&1; then
      apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-compose-plugin || true
    fi
  fi
  docker compose version >/dev/null 2>&1 \
    || die "The 'docker compose' plugin is unavailable. Install it and re-run."
}

# ---- source: use current dir if it's the repo, else clone -----------------
get_source() {
  if [ -f "./docker-compose.yml" ] && [ -f "./Dockerfile" ]; then
    SRC_DIR="$(pwd)"
    log "Using source in current directory: $SRC_DIR"
    return
  fi
  command -v git >/dev/null 2>&1 || {
    if command -v apt-get >/dev/null 2>&1; then
      apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq git
    else
      die "git is required to fetch the source."
    fi
  }
  if [ -d "$INSTALL_DIR/.git" ]; then
    log "Updating existing source in $INSTALL_DIR…"
    git -C "$INSTALL_DIR" pull --ff-only || warn "git pull failed — continuing with existing source."
  else
    log "Cloning $REPO into $INSTALL_DIR…"
    git clone --depth 1 "https://github.com/${REPO}.git" "$INSTALL_DIR"
  fi
  SRC_DIR="$INSTALL_DIR"
}

# ---- config (.env), created once and never clobbered ----------------------
gen_pass()   { od -An -N18 -tx1 /dev/urandom | tr -d ' \n' | cut -c1-16; }
gen_secret() { head -c 32 /dev/urandom | base64; }

write_env() {
  cd "$SRC_DIR"
  if [ -f .env ]; then
    log "Keeping existing config: $SRC_DIR/.env"
    # Make sure APP_PORT reflects what's in the file for the final URL.
    APP_PORT="$(awk -F= '/^APP_PORT=/{print $2}' .env | tr -d ' ' | head -n1)"
    APP_PORT="${APP_PORT:-8080}"
    return
  fi

  local pass="$APP_PASSWORD" secret
  if [ -z "$pass" ] && [ -e /dev/tty ]; then
    read -rsp "Set a panel password (leave blank to auto-generate): " pass </dev/tty || true
    echo
  fi
  if [ -z "$pass" ]; then
    pass="$(gen_pass)"
    GENERATED_PASS="$pass"
  fi
  secret="$(gen_secret)"

  ( umask 077
    cat > .env <<EOF
# xray-manager — generated by docker-install.sh. See .env.example for all options.
APP_PASSWORD=$pass
APP_PORT=$APP_PORT
SESSION_SECRET=$secret
XRAY_INBOUND_PORT=10808
XRAY_INBOUND_HTTP_PORT=10809
EOF
  )
  log "Wrote config to $SRC_DIR/.env"
}

# ---- build + run ----------------------------------------------------------
bring_up() {
  cd "$SRC_DIR"
  mkdir -p data
  log "Building the image and starting the container…"
  log "${C_DIM}(first build downloads the Go toolchain + xray-core; be patient on a Pi)${C_OFF}"
  docker compose up -d --build
}

lan_ip() { hostname -I 2>/dev/null | awk '{print $1}'; }

print_access() {
  local ip; ip="$(lan_ip)"
  echo
  log "Panel is up:  ${C_OK}http://${ip:-<this-host-ip>}:${APP_PORT}${C_OFF}"
  if [ -n "$GENERATED_PASS" ]; then
    warn "Auto-generated password: ${GENERATED_PASS}"
    warn "Change it later by editing $SRC_DIR/.env then: docker compose up -d"
  fi
  echo "${C_DIM}Manage it from $SRC_DIR:  docker compose {logs -f | restart | down}${C_OFF}"
}

main() {
  need_root
  ensure_docker
  get_source
  write_env
  bring_up
  print_access
}

main "$@"
